# Generated by Django 5.0.4 on 2024-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default=None, upload_to='groups/images'),
            preserve_default=False,
        ),
    ]
