# Generated by Django 5.0.4 on 2024-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
