# Generated by Django 5.0.4 on 2024-04-20 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagechat_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='sub_message',
        ),
        migrations.AddField(
            model_name='messagechat',
            name='users_read',
            field=models.ManyToManyField(related_name='users_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
